
import javax.swing.JFrame;
//import DailyEntryManagement11.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shubhra
 */
public class AdminScreen extends javax.swing.JFrame {

    /**
     * Creates new form AdminScreen
     */
    public AdminScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        allStudentDetailsButton = new javax.swing.JButton();
        nightEntryButton = new javax.swing.JButton();
        jButtonDefaulters = new javax.swing.JButton();
        dailyEntryButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));

        allStudentDetailsButton.setText("ALL STUDENT DETAILS");
        allStudentDetailsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allStudentDetailsButtonMouseClicked(evt);
            }
        });
        allStudentDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allStudentDetailsButtonActionPerformed(evt);
            }
        });

        nightEntryButton.setText("NIGHT ENTRY");
        nightEntryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nightEntryButtonMouseClicked(evt);
            }
        });
        nightEntryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nightEntryButtonActionPerformed(evt);
            }
        });

        jButtonDefaulters.setText("VIEW DEFAULTERS");
        jButtonDefaulters.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDefaultersMouseClicked(evt);
            }
        });
        jButtonDefaulters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDefaultersActionPerformed(evt);
            }
        });

        dailyEntryButton1.setText("DAILY ENTRY");
        dailyEntryButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dailyEntryButton1MouseClicked(evt);
            }
        });
        dailyEntryButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dailyEntryButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonDefaulters, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nightEntryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(allStudentDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(86, 86, 86)
                    .addComponent(dailyEntryButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(69, 69, 69)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(allStudentDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nightEntryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDefaulters, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(dailyEntryButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(193, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nightEntryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nightEntryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nightEntryButtonActionPerformed

    private void nightEntryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nightEntryButtonMouseClicked
         NightEntry ob = new  NightEntry();
                    ob.pack();
                    ob.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
                    ob.setVisible(true);
        
        
        
    }//GEN-LAST:event_nightEntryButtonMouseClicked

    private void allStudentDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allStudentDetailsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allStudentDetailsButtonActionPerformed

    private void jButtonDefaultersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDefaultersMouseClicked
         ViewDefaulters ob = new  ViewDefaulters();
                    ob.pack();
                    
                    ob.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
                    ob.setVisible(true);
    }//GEN-LAST:event_jButtonDefaultersMouseClicked

    private void allStudentDetailsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allStudentDetailsButtonMouseClicked
         StudentDetails ob = new  StudentDetails();
                    ob.setVisible(true);
                    ob.pack();
                    ob.setLocationRelativeTo(null);
                    ob.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
    }//GEN-LAST:event_allStudentDetailsButtonMouseClicked

    private void jButtonDefaultersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDefaultersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDefaultersActionPerformed

    private void dailyEntryButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dailyEntryButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dailyEntryButton1MouseClicked

    private void dailyEntryButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dailyEntryButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dailyEntryButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               AdminScreen ob = new AdminScreen();
               ob.pack();
               ob.setLocationRelativeTo(null);
               ob.setVisible(true);
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allStudentDetailsButton;
    private javax.swing.JButton dailyEntryButton1;
    private javax.swing.JButton jButtonDefaulters;
    private javax.swing.JButton nightEntryButton;
    // End of variables declaration//GEN-END:variables
}
