
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Timestamp;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author saumya
 */
public class StudentDailyDetails extends javax.swing.JFrame {

    
    private Connection con;
     private PreparedStatement pst1;
    private PreparedStatement pst;
    private ResultSet rs;
    String reg="",place="";
    private Object dateFormat;
    public StudentDailyDetails(String regNo, String pl) {
        initComponents();
        reg=regNo;
        System.out.println(reg);
        place=pl;
        initialize();
        JtxtPlace.setText(place);
        System.out.println(place);
     
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JtxtRegNo = new javax.swing.JTextField();
        JtxtName = new javax.swing.JTextField();
        JtxtRoomNo = new javax.swing.JTextField();
        JtxtBranch = new javax.swing.JTextField();
        JtxtPlace = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JtxtYear = new javax.swing.JTextField();
        Jtxtstatus = new javax.swing.JTextField();
        Done = new javax.swing.JButton();
        JlblPhoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Registration No");

        jLabel2.setText("Name");

        jLabel3.setText("Room No");

        jLabel4.setText("Branch");

        jLabel5.setText("Place");

        JtxtRegNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxtRegNoActionPerformed(evt);
            }
        });

        JtxtBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxtBranchActionPerformed(evt);
            }
        });

        jLabel6.setText("Year");

        jLabel7.setText("Status");

        Jtxtstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxtstatusActionPerformed(evt);
            }
        });

        Done.setText("Done");
        Done.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DoneMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JtxtRoomNo, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(JtxtRegNo)
                    .addComponent(JtxtName)
                    .addComponent(JtxtBranch, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JtxtPlace, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JtxtYear)
                            .addComponent(Jtxtstatus, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)))
                    .addComponent(JlblPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addComponent(Done)
                .addGap(165, 165, 165))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JtxtRegNo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JtxtName)
                                .addGap(3, 3, 3)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JtxtRoomNo)
                                .addGap(4, 4, 4))))
                    .addComponent(JlblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JtxtBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JtxtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JtxtPlace))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addComponent(Jtxtstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(Done)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    void initialize() {
    try{
    Class.forName("com.mysql.cj.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dailyentrymgmtproject","root","password");
        pst = con.prepareStatement("SELECT * from studentsdetails where regNo=?");//table details
        pst.setString(1, reg);
        //pst.setString(8,place);
        rs = pst.executeQuery();
        //regNo name roomno branch year phone photo
        if(rs.next()){
       
        JtxtRegNo.setText(rs.getString(1));
        JtxtName.setText(rs.getString(2));
        JtxtRoomNo.setText(rs.getString(3));
        JtxtBranch.setText(rs.getString(4)); 
        JtxtYear.setText(rs.getString(5));
        
        //JtxtPlace.setText(rs.getString(6));
        String link = rs.getString(7); 
        System.out.println(link);
        
        ImageIcon img = new ImageIcon(new ImageIcon(link).getImage().getScaledInstance(117, 70, Image.SCALE_DEFAULT));
        JlblPhoto.setIcon(img);
        
        }     
        }
      catch (Exception e) {
                 
                e.printStackTrace();
            }
                
    }
    private void JtxtRegNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxtRegNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxtRegNoActionPerformed

    private void JtxtBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxtBranchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxtBranchActionPerformed

    private void JtxtstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxtstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxtstatusActionPerformed

    private void DoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DoneMouseClicked
         // TODO add your handling code here:
        try{
              
        Class.forName("com.mysql.cj.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/DailyEntryMgmtProject","root","password");
        
        pst1 = con.prepareStatement("SELECT status from dailyentry WHERE regNo=?");
        pst1.setString(1,reg);
            System.out.println("reg1");
       // pst1 = con.prepareStatement(queryCheck);
        pst1.execute();
        String str="";
        
        rs = pst1.executeQuery();
        
        String registerUser="";
        if(rs.next()){
        str=rs.getString(1);
                        
                        System.out.println(str+"**");
                         java.util.Date date = new java.util.Date();
                     
                        if(str.compareTo("Open")==0)    
                        {
                            pst1 = con.prepareStatement("update dailyentry set time=?,place=?,status=? where regNo=?");
                            //pst.setString(1,reg);
                             pst1.setTimestamp(1, new Timestamp(date.getTime()));
                              pst1.setString(2, place);
                            pst1.setString(3,"Close");
                            pst1.setString(4,reg);
                        }
                        else if(str.compareTo("Close")==0)
                        {
                            pst1 = con.prepareStatement("update dailyentry set time=?,place=?,status=? where regNo=?");
                             pst1.setTimestamp(1, new Timestamp(date.getTime()));
                              pst1.setString(2, place);
                            pst1.setString(3,"Open");
                            pst1.setString(4,reg);
                        }
        }
                        else
                        {
                              java.util.Date date = new java.util.Date();
                            System.out.println("&&&");
                            pst1 = con.prepareStatement("insert into dailyentry(regNo,time,place,status) VALUES(?,?,?,?)");
                            pst1.setString(4, "Open");
                             System.out.println("he he ha ha he he ........... he he");
                     
                        pst1.setString(1, reg);
                         System.out.println("reg2");
                        pst1.setTimestamp(2, new Timestamp(date.getTime()));
                        pst1.setString(3, place);
                        }
                          // pst = con.prepareStatement(registerUser);
                           DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");  
                           //LocalDateTime now = LocalDateTime.now();  
  
                       
                       
                        //pst = con.prepareStatement(registerUser);
                        //Calendar cal = Calendar.getInstance();
                       // Jtxtdate.setText(dateFormat.format(cal.getTime()));//dateFormat.format(date));
                         pst1.execute();
                        //Jtxtstatus.setText(str);
                        
          }catch(Exception e){
              System.out.println("Error in \"Done\" execution");
                            e.printStackTrace();
    }                                 
    }//GEN-LAST:event_DoneMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDailyDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDailyDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDailyDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDailyDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDailyDetails().setVisible(true);
            }
        });
*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Done;
    private javax.swing.JLabel JlblPhoto;
    private javax.swing.JTextField JtxtBranch;
    private javax.swing.JTextField JtxtName;
    private javax.swing.JTextField JtxtPlace;
    private javax.swing.JTextField JtxtRegNo;
    private javax.swing.JTextField JtxtRoomNo;
    private javax.swing.JTextField JtxtYear;
    private javax.swing.JTextField Jtxtstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
