
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author saumya
 */
public class ViewDefaulters extends javax.swing.JFrame {
     private Connection con;
    private PreparedStatement pst;
    private ResultSet rs;
    private PreparedStatement pst1;
    private ResultSet rs1;
    /**
     * Creates new form ViewDefaulters
     */
    public ViewDefaulters() {
        initComponents();
        initialise();
    }
    
    void initialise(){
        try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dailyentrymgmtproject","root","password");
        pst = con.prepareStatement("SELECT * from nightentry");
        rs = pst.executeQuery();
        //regNo name roomno branch year phone photo
        while(rs.next()){
            String reg = rs.getString(1);
            String str = rs.getString(2);
            System.out.println(reg);
            String hours = str.substring(11, 13);
            String minutes = str.substring(15, 18);
            System.out.println(hours+" "+minutes);
            String slinhrs="22";
            String elinhrs="23";
            String slinmin="00";
            String elinmin="00";
            
            
            if(hours.compareTo(elinhrs)>=0)
            {
             // System.out.println("hi"+reg);
              pst1 = con.prepareStatement("SELECT * from StudentsDetails where RegNo=?");//table details
              pst1.setString(1, reg);
              rs1 = pst1.executeQuery();
              //regNo name roomno branch year phone photo
              while(rs1.next()){
              String s=(rs1.getString(1))+" "+(rs1.getString(2))+" "+rs1.getString(3)+" "+rs1.getString(4)+
                      " "+rs1.getString(5)+" "+rs1.getString(6);
             // System.out.println("hi"+s);
              jLabel1.setText(jLabel1.getText()+"\n"+s);      
              }
            }
            
        }
        }
        catch(Exception e){
            
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewDefaulters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewDefaulters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewDefaulters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewDefaulters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewDefaulters().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
